services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: programmer
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: users_data_base
    ports:
      - "5432:5432"